name: pr

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yarn lint
        run: |
          yarn install
          yarn build
          yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: |
          yarn install
          yarn test:unit

  test-e2e:
    runs-on: ubuntu-latest
    # Dependabot can't access repo secrets, so this job always fails when
    # created by Dependabot. We just skip it.
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn build
      - name: Run E2E tests and send coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverage
