name: pr

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yarn lint
        run: |
          yarn install
          yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: |
          yarn install
          yarn test:unit

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - name: Run E2E tests and send coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverage
